import type { DomainConfiguration, Observation } from "../domain-config";
import { configurationFor, MEASUREMENTS } from "./domain-config-cases";
import type { SeedParticipation } from "../step9-contract";

/** Explicit synthetic consent fixture, never derived from recorded value shape. */
export function approvedSeedParticipation(c:DomainConfiguration):SeedParticipation {
  return {
    recipe:"duration-plus-distinct-qualifying-days-v1",approved:true,
    organizationId:c.organizationId,ownerUserId:c.ownerUserId,domainId:c.domainId,
    policyVersionId:c.policyVersionId,targetId:c.targets.normal.targetId,
    components:[
      {kind:"quantity",measurementId:c.measurements[0].measurementId,weight:0.5,mandatory:true},
      {kind:"frequency",measurementId:"qualifying-days",weight:0.5,mandatory:true},
    ],
  };
}

/** Synthetic only. 50 is a proposal; 70 remains the saved-profile example. */
export function meditation(weeklyMinutes: 50 | 70 = 50): DomainConfiguration {
  const c=configurationFor("synthetic-meditation",MEASUREMENTS[0],10);
  c.domainId="arbitrary-domain-9f2c";c.displayName="Meditation";
  c.effectiveFrom="2025-01-01T00:00:00.000Z";
  c.boundary={timezone:"UTC",dayStartHour:0};
  c.measurements.push({
    measurementId:"qualifying-days",displayName:"Practice days",meaning:"Distinct qualifying logical days",
    kind:"frequency",role:"practice",unit:{unitId:"day",dimension:"days"},valueType:"integer",
    aggregation:"count",comparisonDirection:"higher_is_better",countBy:"distinct_days",scope:{kind:"period",windowDays:7},
  });
  c.qualification={kind:"condition",condition:{
    measurementId:c.measurements[0].measurementId,unitId:"minute",valueType:"number",basis:{kind:"per_event"},
    constraint:{operator:"gte",value:10},
  }};
  c.targets.normal.conditions=[
    {measurementId:c.measurements[0].measurementId,unitId:"minute",valueType:"number",basis:{kind:"period",windowDays:7},
      periodAggregation:{sourceBasis:"per_event",method:"sum"},constraint:{operator:"gte",value:weeklyMinutes}},
    {measurementId:"qualifying-days",unitId:"day",valueType:"integer",basis:{kind:"period",windowDays:7},constraint:{operator:"gte",value:5}},
  ];
  return c;
}
export function practices(c:DomainConfiguration,days:number,minutes:number,perDay=1):Observation[] {
  return Array.from({length:days},(_,i)=>Array.from({length:perDay},(_,j)=>({
    schemaVersion:1 as const,observationId:`synthetic-${i}-${j}`,organizationId:c.organizationId,ownerUserId:c.ownerUserId,
    domainId:c.domainId,policyVersionId:c.policyVersionId,observedAt:`2026-01-${String(i+1).padStart(2,"0")}T${j===0?"12":"16"}:00:00Z`,
    values:{[c.measurements[0].measurementId]:{unitId:"minute",valueType:"number" as const,value:minutes}},
  }))).flat();
}
/** Hand-computed, reviewable expected values, not generated by the oracle. */
export const MEDITATION_EXAMPLES = [
  {label:"five days of ten",days:5,minutes:10,perDay:1,quantity:50,qualifyingDays:5,score50:50,condition50:"Warning",score70:300/7,condition70:"Critical"},
  {label:"six days of ten",days:6,minutes:10,perDay:1,quantity:60,qualifyingDays:6,score50:60,condition50:"Warning",score70:360/7,condition70:"Warning"},
  {label:"ten days of ten",days:10,minutes:10,perDay:1,quantity:100,qualifyingDays:10,score50:100,condition50:"Healthy",score70:600/7,condition70:"Needs Attention"},
  {label:"four days of twenty-five",days:4,minutes:25,perDay:1,quantity:100,qualifyingDays:4,score50:70,condition50:"Warning",score70:390/7,condition70:"Warning"},
  {label:"ten practices on five days",days:5,minutes:10,perDay:2,quantity:100,qualifyingDays:5,score50:75,condition50:"Needs Attention",score70:425/7,condition70:"Warning"},
] as const;
